apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tls-certificate
  namespace: pgweb
spec:
  secretName: web-ssl
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  dnsNames:
  - pgweb.shopups2.xyz