replicaCount: 1
image:
  repository: gcr.io/disaster-recovery-test-370104/pgweb
  pullPolicy: IfNotPresent
  tag: main-28
imagePullSecrets: []
nameOverride: ''
fullnameOverride: ''
serviceAccount:
  create: true
  annotations: {}
  name: ''
podAnnotations: {}
podSecurityContext: {}
securityContext: {}
service:
  type: LoadBalancer
  port: 80
ingress:
  enabled: true
  className: ''
  annotations: {}
  hosts:
    - host: pgweb.shopups2.xyz
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
resources: {}
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
nodeSelector: {}
tolerations: []
affinity: {}
env: []
extraArgs: []
