replicaCount: 1
image:
  repository: gcr.io/disaster-recovery-test-370104/pgweb
  pullPolicy: IfNotPresent
  tag: main-31
imagePullSecrets: []
nameOverride: ''
fullnameOverride: ''
serviceAccount:
  create: true
  annotations: {}
  name: ''
podAnnotations: {}
podSecurityContext: {}
securityContext: {}
service:
  type: LoadBalancer
  port: 80
ingress:
  enabled: true
  className: ''
  hosts:
    - host: pgweb.shopups2.xyz
      paths:
        - path: /
          pathType: ImplementationSpecific
<<<<<<< HEAD
  tls: 
    - secretName: tls-secret
=======
  tls:
    - secretName: web-ssl
>>>>>>> 9ad3365ee851d82a93e299e555ede5633e81d145
      hosts:
        - pgweb.shopups2.xyz
resources: {}
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
nodeSelector: {}
tolerations: []
affinity: {}
env: []
extraArgs: []
