name: pgweb cd

on:
  workflow_run:
    workflows: ["pgweb ci"]
    branches: [ main ]
    types:
      - completed
env:
  SOURCE_BRANCH_NAME: ${{ github.event.pull_request.head.ref }}
  IMAGE_TAG: $SOURCE_BRANCH_NAME-$GITHUB_RUN_NUMBER

jobs:
  setup-build-publish-deploy-production:
    name: Setup, Build, Publish, and Deploy to production
    runs-on: ubuntu-20.04

    steps:
    - name : checkout 
      uses: 'actions/checkout@v3'

    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: '${{ secrets.SERVICE_ACCOUNT }}'

    - uses: google-github-actions/setup-gcloud@v0

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v0

    - run: |-
        gcloud --quiet auth configure-docker

    - id: 'get-credentials'
      uses: 'google-github-actions/get-gke-credentials@v1'
      with:
        cluster_name: 'example-cluster'
        location: 'us-central1-a'
      

    - name: install helm release
      run: |-
        kubectl apply -f helm/issuer.yaml
        helm upgrade --install pgweb helm -n pgweb
