name: pgweb

on: [push]
    #branches: [main]
env:
  SOURCE_BRANCH_NAME: ${{ github.event.pull_request.head.ref }}

jobs:
  setup-build-publish-deploy-production:
    name: Setup, Build, Publish, and Deploy to production
    runs-on: ubuntu-20.04

    steps:
    - name : checkout 
      uses: 'actions/checkout@v3'

    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: '${{ secrets.SERVICE_ACCOUNT }}'

    - uses: google-github-actions/setup-gcloud@v0

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v0

    - run: |-
        gcloud --quiet auth configure-docker

    - name: Build Docker image
      run: |-
        IMAGE_TAG=${GITHUB_REF##*/}-$GITHUB_RUN_NUMBER
        docker build -t pgweb .
        docker tag pgweb gcr.io/disaster-recovery-test-370104/pgweb:$IMAGE_TAG
        docker push gcr.io/disaster-recovery-test-370104/pgweb:$IMAGE_TAG

          
